(MAKE-PACKAGE "qi")
(LOAD "qi.lisp")
(COMPILE-FILE "qi.lisp")
(LET ((Imp (LISP-IMPLEMENTATION-TYPE)))
   (COND ((EQUAL Imp "CLISP") (LOAD "qi.fas"))
                  ((EQUAL Imp "CMU Common Lisp") (LOAD "qi.x86f"))))
(save)
(FORMAT T "~%Installation finished; hit RETURN.")
(READ-CHAR)
(quit)
